CREATE TABLE Author
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE Category
(
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
);

CREATE TABLE Book
(
	Id UNIQUEIDENTIFIER NOT NULL,
	Title VARCHAR(50) NOT NULL,
	IdAuthor UNIQUEIDENTIFIER NOT NULL,
	IdCategory UNIQUEIDENTIFIER NOT NULL,
	PublishedYear INT NOT NULL,

	CONSTRAINT FK_Book_IdAuthor_Author_Id FOREIGN KEY (IdAuthor) REFERENCES Author(Id),
	CONSTRAINT FK_Book_IdCategory_Category_Id FOREIGN KEY (IdCategory) REFERENCES Category(Id)
);

